export const Upgrades = {
  // General Hunter
  HUNTER_WEAK_BONE_BLADES: "HUNTER_WEAK_BONE_BLADES",
  HUNTER_NORMAL_BONE_BLADES: "HUNTER_NORMAL_BONE_BLADES",
  HUNTER_STRONG_BONE_BLADES: "HUNTER_STRONG_BONE_BLADES",

  HUNTER_BABY_WYVERN_GRIPS: "HUNTER_BABY_WYVERN_GRIPS",
  HUNTER_WYVERN_GRIPS: "HUNTER_WYVERN_GRIPS",
  HUNTER_DRAGON_GRIPS: "HUNTER_DRAGON_GRIPS",

  HUNTER_WEAK_BONE_BOWS: "HUNTER_WEAK_BONE_BOWS",
  HUNTER_NORMAL_BONE_BOWS: "HUNTER_NORMAL_BONE_BOWS",
  HUNTER_STRONG_BONE_BOWS: "HUNTER_STRONG_BONE_BOWS",

  HUNTER_WEAK_ARMOR: "HUNTER_WEAK_ARMOR",
  HUNTER_NORMAL_ARMOR: "HUNTER_NORMAL_ARMOR",
  HUNTER_STRONG_ARMOR: "HUNTER_STRONG_ARMOR",
  HUNTER_ARMOR_SPIKES: "HUNTER_ARMOR_SPIKES",

  // Plains Hunter
  PLAINS_HUNTER_CAMO: "PLAINS_HUNTER_CAMO",
  PLAINS_HUNTER_NETTING: "PLAINS_HUNTER_NETTING",
  PLAINS_HUNTER_PIT_TRAPS: "PLAINS_HUNTER_PIT_TRAPS",
  PLAINS_HUNTER_SPIKED_PIT_TRAPS: "PLAINS_HUNTER_SPIKED_PIT_TRAPS",
  PLAINS_HUNTER_WEAK_LEATHER_BOOTS: "PLAINS_HUNTER_WEAK_LEATHER_BOOTS",
  PLAINS_HUNTER_SPIKED_GLOVES: "PLAINS_HUNTER_SPIKED_GLOVES",
} as const;

export type Upgrade = keyof typeof Upgrades;

export const UpgradeCategories = {
  GENERAL_HUNTER_UPGRADES: "GENERAL_HUNTER_UPGRADES",
  PLAIN_HUNTER_UPGRADES: "PLAIN_HUNTER_UPGRADES",
} as const;

export type UpgradeCategory = keyof typeof UpgradeCategories;

const generalHunterUpgrades = new Set([
  Upgrades.HUNTER_WEAK_BONE_BLADES,
  Upgrades.HUNTER_NORMAL_BONE_BLADES,
  Upgrades.HUNTER_STRONG_BONE_BLADES,

  Upgrades.HUNTER_WEAK_BONE_BOWS,
  Upgrades.HUNTER_NORMAL_BONE_BOWS,
  Upgrades.HUNTER_STRONG_BONE_BOWS,

  Upgrades.HUNTER_BABY_WYVERN_GRIPS,
  Upgrades.HUNTER_WYVERN_GRIPS,
  Upgrades.HUNTER_DRAGON_GRIPS,

  Upgrades.HUNTER_WEAK_ARMOR,
  Upgrades.HUNTER_NORMAL_ARMOR,
  Upgrades.HUNTER_STRONG_ARMOR,
  Upgrades.HUNTER_ARMOR_SPIKES,
]);
const plainsHunterUpgrades = new Set([
  Upgrades.PLAINS_HUNTER_CAMO,
  Upgrades.PLAINS_HUNTER_NETTING,
  Upgrades.PLAINS_HUNTER_PIT_TRAPS,
  Upgrades.PLAINS_HUNTER_SPIKED_PIT_TRAPS,
  Upgrades.PLAINS_HUNTER_WEAK_LEATHER_BOOTS,
  Upgrades.PLAINS_HUNTER_SPIKED_GLOVES,
]);

export const UpgradeCategoriesMap = new Map<UpgradeCategory, Set<Upgrade>>([
  [UpgradeCategories.GENERAL_HUNTER_UPGRADES, generalHunterUpgrades],
  [UpgradeCategories.PLAIN_HUNTER_UPGRADES, plainsHunterUpgrades],
]);
