name: CI

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install
        run: npm install
      - name: Eslint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install
        run: npm install
      - name: Build Sass
        run: npm run sass
      - name: Build Typescript
        run: npm run compile
      - name: Webpack
        run: npm run pack
      - name: Test
        run: npm run test
